//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRCodeRedirects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRCodeRedirect
    {
        public string QRCodeId { get; set; }
        public string WidenURL { get; set; }
    }
}
